# Generated by Django 2.1.7 on 2019-03-13 01:57

import analytics.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_lap', models.IntegerField()),
                ('to_lap', models.IntegerField()),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('free_pass', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_born', models.DateField()),
                ('home', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_lap', models.IntegerField()),
                ('to_lap', models.IntegerField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laps_lead', to='analytics.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('distance', models.IntegerField()),
                ('scheduled_distance', models.FloatField()),
                ('laps_run', models.IntegerField()),
                ('scheduled_laps', models.IntegerField()),
                ('lap_distance', models.FloatField()),
                ('length', models.TimeField()),
                ('date', models.DateField()),
                ('surface', models.CharField(choices=[('P', 'Paved'), ('R', 'Road'), ('D', 'Dirt')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_position', models.IntegerField()),
                ('finishing_position', models.IntegerField()),
                ('sponsor', models.CharField(blank=True, max_length=100, null=True)),
                ('car', models.IntegerField(choices=[(1, 'Ford'), (2, 'Chevrolet'), (3, 'Toyota'), (4, 'Dodge'), (5, 'Pontiac'), (6, 'Plymouth'), (7, 'Mercury'), (8, 'Oldsmobile'), (9, 'Matador')])),
                ('number', models.IntegerField()),
                ('laps_completed', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, 'Running'), (2, 'Crash'), (3, 'Mechanical'), (4, 'Parked')])),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='analytics.Driver')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Owner')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Race')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[(analytics.models.StateChoice('Alabama'), 'Alabama'), (analytics.models.StateChoice('Alaska'), 'Alaska'), (analytics.models.StateChoice('Arizona'), 'Arizona'), (analytics.models.StateChoice('Arkansas'), 'Arkansas'), (analytics.models.StateChoice('California'), 'California'), (analytics.models.StateChoice('Colorado'), 'Colorado'), (analytics.models.StateChoice('Connecticut'), 'Connecticut'), (analytics.models.StateChoice('Delaware'), 'Delaware'), (analytics.models.StateChoice('Florida'), 'Florida'), (analytics.models.StateChoice('Georgia'), 'Georgia'), (analytics.models.StateChoice('Hawaii'), 'Hawaii'), (analytics.models.StateChoice('Idaho'), 'Idaho'), (analytics.models.StateChoice('Illinois'), 'Illinois'), (analytics.models.StateChoice('Indiana'), 'Indiana'), (analytics.models.StateChoice('Iowa'), 'Iowa'), (analytics.models.StateChoice('Kansas'), 'Kansas'), (analytics.models.StateChoice('Kentucky'), 'Kentucky'), (analytics.models.StateChoice('Louisiana'), 'Louisiana'), (analytics.models.StateChoice('Maine'), 'Maine'), (analytics.models.StateChoice('Maryland'), 'Maryland'), (analytics.models.StateChoice('Massachusetts'), 'Massachusetts'), (analytics.models.StateChoice('Michigan'), 'Michigan'), (analytics.models.StateChoice('Minnesota'), 'Minnesota'), (analytics.models.StateChoice('Mississippi'), 'Mississippi'), (analytics.models.StateChoice('Missouri'), 'Missouri'), (analytics.models.StateChoice('Montana'), 'Montana'), (analytics.models.StateChoice('Nebraska'), 'Nebraska'), (analytics.models.StateChoice('Nevada'), 'Nevada'), (analytics.models.StateChoice('New Hampshire'), 'New Hampshire'), (analytics.models.StateChoice('New Jersey'), 'New Jersey'), (analytics.models.StateChoice('New Mexico'), 'New Mexico'), (analytics.models.StateChoice('New York'), 'New York'), (analytics.models.StateChoice('North Carolina'), 'North Carolina'), (analytics.models.StateChoice('North Dakota'), 'North Dakota'), (analytics.models.StateChoice('Ohio'), 'Ohio'), (analytics.models.StateChoice('Oklahoma'), 'Oklahoma'), (analytics.models.StateChoice('Oregon'), 'Oregon'), (analytics.models.StateChoice('Pennsylvania'), 'Pennsylvania'), (analytics.models.StateChoice('Rhode Island'), 'Rhode Island'), (analytics.models.StateChoice('South Carolina'), 'South Carolina'), (analytics.models.StateChoice('South Dakota'), 'South Dakota'), (analytics.models.StateChoice('Tennessee'), 'Tennessee'), (analytics.models.StateChoice('Texas'), 'Texas'), (analytics.models.StateChoice('Utah'), 'Utah'), (analytics.models.StateChoice('Vermont'), 'Vermont'), (analytics.models.StateChoice('Virginia'), 'Virginia'), (analytics.models.StateChoice('Washington'), 'Washington'), (analytics.models.StateChoice('West Virginia'), 'West Virginia'), (analytics.models.StateChoice('Wisconsin'), 'Wisconsin'), (analytics.models.StateChoice('Wyoming'), 'Wyoming')], max_length=5)),
                ('distance', models.FloatField()),
                ('type', models.IntegerField(verbose_name=((1, 'Short Track'), (2, 'Intermediate'), (3, 'Superspeedway'), (4, 'Road Course')))),
            ],
        ),
        migrations.AddField(
            model_name='race',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='analytics.Track'),
        ),
        migrations.AddField(
            model_name='leader',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='analytics.Race'),
        ),
        migrations.AddField(
            model_name='caution',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cautions', to='analytics.Race'),
        ),
    ]
